//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamNotification.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disciplinas()
        {
            this.ProvasTrabalhos = new HashSet<ProvasTrabalhos>();
        }
    
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public int Codigo_Curso { get; set; }
    
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvasTrabalhos> ProvasTrabalhos { get; set; }
    }
}
