//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamNotification.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvasTrabalhos
    {
        public int ID { get; set; }
        public int Id_disciplina { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data_final { get; set; }
        public System.DateTime Data_aviso { get; set; }
    
        public virtual Disciplinas Disciplinas { get; set; }
    }
}
